### PR TITLE
Week 10 day 03 mod 02

### PR DESCRIPTION
**Pull request by eerwitt**
Still working on solutions.

Goal is to go over two examples one line of code at a time. I'm hoping this may help people understand and retain the vocabulary.

The code is in JSFiddles, I did this because I'm hoping it'll focus on exactly what we're doing instead of all the Angular parts.

### CODE REVIEW

**Comment by cameronjacoby** [comment]
@eerwitt This looks great to me! I like that you're using JSFiddle here.

Since the challenges for this module are also their HW for the night, could you create a separate repo so they can make a PR? Maybe you can give them the option to create a full Angular app or send a PR with a like to JSFiddle if they choose to do it that way?

**Comment by eerwitt** [comment]
@cameronjacoby good call, I'll do that.

**Comment by eerwitt** [comment]
@cameronjacoby updated with link to homework.

**Comment by cameronjacoby** [comment]
@eerwitt This is great! :+1:

**Comment by eerwitt** [comment]
@cameronjacoby Please don't look at my styles. So bad, there isn't even bootstrap included :/

**Comment by cameronjacoby** [comment]
@eerwitt It's minimalist, like Craigslist.

**Pull request merged**
