### PR TITLE
Week 10 day 04 mod 02

### PR DESCRIPTION
**Pull request by eerwitt**
This module is about giving an overview of some of the ways in which you can host your Angular App which may not be the norm.

I can't think of a way to add solutions for the homework because it is all about getting something setup quickly on some site other than heroku. @cameronjacoby any ideas?

I don't plan to go over all these services but give a high level definition of each and talk over them. I was thinking of doing a tutorial but the steps are covered in the links.

Any other thoughts are useful.

### CODE REVIEW

**Comment by ben-manning** [comment]
@eerwitt I think it might be okay for there to be no solutions in the repo seeing as there are a lot of different directions to go in.  It might be cool to have the students (whether or not they complete the task) highlight issues they ran into while attempting to create an app in this manner.

**Comment by eerwitt** [comment]
Great idea, I'll add that to the homework requirement too.

**Comment by ben-manning** [comment]
@eerwitt The notes are great though and the articles that are linked there paint a really good picture of the different complexities or outcomes that are encountered here.

**Comment by eerwitt** [comment]
@cameronjacoby updated with a bit about HTML5 Pushstate.

**Comment by cameronjacoby** [comment]
@eerwitt This looks great - thanks for making the changes!

I'm going to merge this in, but just be aware that I basically told them to use push state this morning and told them that it was a better UX to have client-side routing working even with page refreshes. :grin:

**Comment by eerwitt** [comment]
@cameronjacoby haha I'll reiterate what you've said in the lesson because it is correct.

**Pull request merged**
