### PR TITLE
Week 01 day 02 drill

### LINKED ISSUE #5: day-02-drill
Create a drill about debugging JS:

```
Debug Broken Code and/or JS Data Types Challenges

Note: Use or get inspiration from Codewars
```

Also post the code to JSFiddle.

### PR DESCRIPTION
**Pull request by eerwitt**
First set of drills.

resolves #5

### CODE REVIEW

**Comment by eerwitt** [comment]
references #5

**Comment by eerwitt** [comment]
@ben-manning when you have some time, could you please try a few of these and see what you think?

**Comment by cameronjacoby** [comment]
@eerwitt 

+1

I think this looks awesome. Nice job! :+1: 

This is a really small formatting thing, but it's nice for students if links to external sources open in new tabs. I usually use an HTML anchor tag instead of the markdown links, because I couldn't find a way to do new tabs in markdown.

**Comment by eerwitt** [comment]
@cameronjacoby good idea, I'll change that now.

**Comment by eerwitt** [comment]
@cameronjacoby & @ben-manning updated taking into account feedback. Please let me know what you think.

Also, if you end up with a bunch of markdown links, I made two zsh functions which can be used in a pre-commit hook to replace links with a `target="_blank"`.

``` zsh
function tbl { sed -E -i -e 's/([^!])\[([^]]+)\]\(([^)]+)\)/\1<a href="\3" target="_blank">\2<\/a>/g' $1 }
function ibl { sed -E -i -e 's/\[!\[([^]]+)\]\(([^)]+)\)\]\(([^)]+)\)/<a href="\2" target="_blank"><img src="\2" alt="\1"><\/a>/g' $1 }
```

**Comment by ben-manning** [comment]
Looks good to me :+1:

**Pull request merged**
