### PR TITLE
Week 02 day 01 mod 02

### PR DESCRIPTION
**Pull request by ben-manning**
I'm fairly confident with the lecture and how it ties into the HW.  However, I just need to see if I should add a few exercises in the lecture to connect the two.

### CODE REVIEW

**Comment by cameronjacoby** [comment]
This looks great! Your inclination is right to add a few challenges to bridge the lesson and the HW. I would add 2-3 challenges that have them using iterators and make sure they're super comfortable with the callback structure before having them start the HW.

I think the HW is going to be really challenging. Not necessarily a bad thing, but maybe move questions 5 & 6 to optional stretch as well? Six iterators is a lot to implement from scratch - I think four is more manageable, which the last three as stretch.

**Comment by ben-manning** [comment]
Right on.  I've got three basic challenges in the notes now.  My plan is to have them work on those challenges and review the structure after the fact.  After that I'll segue into the HW

**Comment by cameronjacoby** [comment]
Perfect! Can you add solutions for these challenges as well?

**Comment by ben-manning** [comment]
Got the solutions in!

**Pull request merged**
