### PR TITLE
week-07-day-04-mod-01

### PR DESCRIPTION
**Pull request by ben-manning**
Testing with RSpec:  This lesson is taken from the WDI-22-23 track.  Everything looks good to me.  I just need to link it to a repo where they can submit a pull request when they are done with it.

### CODE REVIEW

**Comment by cameronjacoby** [comment]
@ben-manning FYI this is what I have planned for the afternoon: https://github.com/sf-wdi-24/testing_inventory

Let me know if that works or if I should change anything to make it more consistent with the morning!

**Comment by ben-manning** [comment]
@cameronjacoby I think that totally works for them in the afternoon!!!

**Comment by ben-manning** [comment]
I have to create a link to my repo for the morning.  I think they'll be doing a lot of testing on this day.  Other than creating the link and repo I think this guy is good to go.

**Comment by ben-manning** [comment]
I think we're good to go.

**Comment by cameronjacoby** [comment]
@ben-manning This looks awesome overall. It actually works out perfectly since they'll get a chance to write both model and controller tests in the morning, then the afternoon is a heavier focus on controllers.

Two small edits:
- Can you edit the challenges repo (`rspec_testing_app`) to make it so that the Rails app (`rspec_testing`) isn't nested inside? It'll just be easier for them to get started after cloning if the root directory is the actual Rails app.
- Can you add a `solutions.md` file to this module as well with just a link to the `solutions` branch of the challenges repo: https://github.com/sf-wdi-24/rspec_testing_app/tree/solutions

**Comment by ben-manning** [comment]
@cameronjacoby Everything is changed and ready to roll.

**Comment by cameronjacoby** [comment]
Thanks @ben-manning ! :+1:

**Pull request merged**
